# Generated by Django 5.1.1 on 2024-09-29 12:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=254, null=True)),
                ('body', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=254, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField(help_text='<b>Note: </b>score should be between 1 to 5')),
                ('comment', models.TextField(blank=True, null=True)),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='score_handler.content')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='score_handler.user')),
            ],
        ),
        migrations.CreateModel(
            name='ContentScoreAggregator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('count_of_score', models.IntegerField(default=0)),
                ('average_of_score', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=5)),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='score_handler.score')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['user', 'content'], name='score_handl_user_id_6a137f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('user', 'content')},
        ),
    ]
